name: Playwright CI
permissions: {}
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: E2E Tests with Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Create .env file
        run: | 
          echo "DATABASE_PATH=\"file:./test.db\"" > .env
          echo "S3_ENDPOINT=\"https://DUMMY.r2.cloudflarestorage.com/ariax-dummy\"" >> .env
          echo "S3_BUCKET=\"ariax-dummy\"" >> .env
          echo "S3_ACCESS_KEY_ID=\"DUMMY\"" >> .env
          echo "S3_SECRET_ACCESS_KEY=\"DUMMY\"" >> .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run pnpm build
        run: pnpm build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Execute Prisma migrations
        run: pnpm exec prisma migrate deploy

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-node-${{ matrix.node-version }}
          path: playwright-report/
          retention-days: 30
